<?php
/**
 * @file
 * Contains hooks for the module for Administrative Enhancements.
 */

use Symfony\Component\Yaml\Yaml;

/**
 * Callable custom function to update / override existing config from what is on disk in the module.
 *
 * @param string $configName
 *   The configuration name.
 * @param bool $hasUUID
 *   Whether to check / generate a UUID for the configuration.
 * @param string $location
 *   The location of the configuration file.
 *
 * @return void
 */
function _pq_starter_admin_override_config(string $configName, bool $hasUUID = TRUE, string $location = '/config/optional/') {
  $existingConfig = \Drupal::configFactory()->getEditable($configName);
  if ($existingConfig) {
    if ($hasUUID) {
      // Get the UUID that already exists. If it doesn't, generate a new one.
      $uuid = $existingConfig->get('uuid');
      if (!$uuid) {
        $uuid = \Drupal::service('uuid')->generate();
      }
    }

    $modulePath = \Drupal::moduleHandler()->getModule('pq_starter_admin')->getPath();

    $file = DRUPAL_ROOT . '/' . $modulePath . $location . $configName . '.yml';
    if (file_exists($file)) {
      $fileConfig = Yaml::parseFile($file);

      $newConfig = ($hasUUID ? array_merge(['uuid' => $uuid], $fileConfig) : $fileConfig);

      $existingConfig->setData($newConfig);
      $existingConfig->save();
    }
    else {
      \Drupal::logger('pq_starter_admin')->warning('Config file not found: ' . $configName);
    }
  }
}